// write a program to print ascii values of the character//
#include<iostream.h>
#include<conio.h>
void main()
{
  clrscr();
  // variable for character
   char ch,static_cast;

   // get user input for character
   cout<<"enter a character:";
   cin>>ch;

   // print ascii values of the character

   cout<<"ascii value of";
   cout<<ch<<"is"<<static_cast<<int(ch)<<endl;
   getch();
}